[platformio]
default_envs = esp32_calibrador

[env:esp32_calibrador]
platform      = espressif32
board         = esp32dev
framework     = arduino
board_build.filesystem = littlefs

lib_extra_dirs = ../lib_shared
lib_ldf_mode   = deep+

build_src_filter = +<*> -<main_old.cpp> -<Func_*.cpp> +<Func_Pulsadores.cpp> +<Func_Mensajes.cpp> +<Func_Mediciones_v4.cpp>

build_flags =
    -DFW_VERSION=\"0.1.0\"
    -Iinclude

    ; -DRED_WIFI=\"tu_red\"
    ; -DCLAVE_WIFI=\"tu_clave\"

lib_deps =
    knolleary/PubSubClient
    marvinroger/AsyncMqttClient
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    dfrobot/DFRobotDFPlayerMini@^1.0.6
    ldab/esp32_ftpclient @ ^0.1.4